apiVersion: v1
kind: PersistentVolume
metadata:
  name: fio-tests
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/centos/kubestorage/fio-tests
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker-1 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-tests
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
      requests:
        storage: 2Gi
  storageClassName: local-storage
  volumeName: fio-tests


