#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: longhorn-rwx-test
#spec:
#  volumeName: "longhorn-rwx"
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 2Gi
#---
apiVersion: batch/v1
kind: Job
metadata:
  name: longhorn-rwx-test
spec:
  template:
    spec:
      containers:
      - name: longhorn-rwx-test
        image: svallero/fio-plot:0.0
        command: ["/bin/sh"]
        args: ["-c","cd /fio-plot/benchmark_script; ./bench_fio --target /longhorn-rwx --type directory --template fio-job-template.fio --iodepth 1 --numjobs 1 --runtime 30 --mode randread randwrite --output /outputs --size 1G -b 4k"]
        volumeMounts:
        - name: test-dir
          mountPath: /longhorn-rwx
        - name: outputs-dir
          mountPath: /outputs
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-worker-1
      restartPolicy: Never
      volumes:
      - name: test-dir
        persistentVolumeClaim:
          claimName: longhorn-rwx-test
      - name: outputs-dir
        persistentVolumeClaim:
          claimName: test-rwx
  backoffLimit: 10
