apiVersion: v1
kind: Service
metadata:
  name: make-plots
  labels:
    app: make-plots
spec:
  ports:
  - port: 8000
    name: http
    nodePort: 31050
  #clusterIP: None
  type: NodePort
  selector:
    app: make-plots
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: make-plots
spec:
  serviceName: make-plots
  replicas: 1
  selector:
    matchLabels:
      app: make-plots
  template:
    metadata:
      labels:
        app: make-plots
    spec:
      containers:
      - name: make-plots
        image: svallero/fio-plot:0.0
        command: ["/bin/sh"]
        args: ["-c","cd /fio-plot/fio_plot/plots; python3 -m http.server 8000"]
        volumeMounts:
        - name: outputs-dir
          mountPath: /outputs
        - name: plots-dir
          mountPath: /fio-plot/fio_plot/plots
      volumes:
      - name: outputs-dir
        persistentVolumeClaim:
          claimName: outputs-test
  volumeClaimTemplates:
  - metadata:
      name: plots-dir
    spec:
      storageClassName: longhorn
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

