apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outputs-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: test-rwx
